language: go

go:
 - 1.12.x

env:


script:
 - sh build.sh
 - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
 - go vet ./...

after_success:
 - bash <(curl -s https://codecov.io/bash)
