language: go

go:
 - 1.12.x

before_script:
 - go run ./assets/asset_generate.go

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
 - go vet ./...

after_success:
 - bash <(curl -s https://codecov.io/bash)
